$.lang.register('chatmoderator.usage.toggles', 'jak używać: !moderation [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker / regulars / subscribers / silenttimeout]');
$.lang.register('chatmoderator.usage.messages', 'jak używać: !moderation [linksmessage / capsmessage / symbolsmessage / spammessage / emotesmessage / colorsmessage / blacklistmessage / longmsgmessage / spamtrackermessage]');
$.lang.register('chatmoderator.options', 'jak używać: !moderation [capstriggerlength / capslimit / symbolstriggerlength / symbolslimit / symbolsgrouplimit / spamlimit / emoteslimit / spamtrackerlimit / spamtrackertime / permittime / warningtime / timeouttime / messagecooldown / messagecharacterlimit / blacklisttimeouttime / warningresettime]');
$.lang.register('chatmoderator.link.usage', 'jak używać: !moderation links [on / off] (link filter is currently $1)');
$.lang.register('chatmoderator.link.filter.enabled', 'link filter has been enabled.');
$.lang.register('chatmoderator.msgcooldown.usage', 'jak używać: !moderation messagecooldown [czas w sekundach]');
$.lang.register('chatmoderator.msgcooldown.set', 'opóźnienie wiadomości ustawiono na $1 sekund.');
$.lang.register('chatmoderator.warningresettime.usage', 'jak używać: !moderation warningresettime [czas w minutach]');
$.lang.register('chatmoderator.warningresettime.set', 'opóźnienie dla ostrzeżeń ustawiono na $1 minut.');
$.lang.register('chatmoderator.link.filter.disabled', 'filtr linków został wyłączony.');
$.lang.register('chatmoderator.message.limit.usage', 'jak używać: !moderation messagecharacterlimit [ilość]');
$.lang.register('chatmoderator.message.limit.set', 'maksymalna ilośc znaków w zdaniu ustawiona na $1 znaków.');
$.lang.register('chatmoderator.message.message.usage', 'jak używać: !moderation longmsgmessage [message]');
$.lang.register('chatmoderator.message.message.set', 'długa wiadomość ustawiona na $1');
$.lang.register('chatmoderator.message.usage', 'jak używać: !moderation longmessages [on / off] (filtr długich wiadomości jest teraz $1)');
$.lang.register('chatmoderator.message.filter.enabled', 'włączono filtr długich wiadomości.');
$.lang.register('chatmoderator.message.filter.disabled', 'wyłączono filtr długich wiadomości.');
$.lang.register('chatmoderator.caps.usage', 'jak używać: !moderation caps [on / off] (filtr wielkich liter jest $1)');
$.lang.register('chatmoderator.caps.filter.enabled', 'włączono filtr wielkich liter.');
$.lang.register('chatmoderator.caps.filter.disabled', 'wyłączono filtr wielkich liter.');
$.lang.register('chatmoderator.spam.usage', 'jak używać: !moderation spam [on / off] (filtr spamu jest teraz $1)');
$.lang.register('chatmoderator.spam.filter.enabled', 'włączono filtr spamu.');
$.lang.register('chatmoderator.spam.filter.disabled', 'wyłączono filtr spamu.');
$.lang.register('chatmoderator.spamtracker.usage', 'jak używać: !moderation spamtracker [on / off] (śledzenie spamu jest teraz $1)');
$.lang.register('chatmoderator.spamtracker.filter.enabled', 'filtr śledzenia spamu został włączony.');
$.lang.register('chatmoderator.spamtracker.filter.disabled', 'filtr śledzenia spamu został wyłączony.');
$.lang.register('chatmoderator.symbols.usage', 'jak używać: !moderation symbols [on / off] (filtr symboli jest teraz $1)');
$.lang.register('chatmoderator.symbols.filter.enabled', 'filtr symboli został włączony.');
$.lang.register('chatmoderator.symbols.filter.disabled', 'filtr symboli został wyłączony.');
$.lang.register('chatmoderator.emotes.usage', 'jak używać: !moderation emotes [on / off] (filtr emotek jest teraz $1)');
$.lang.register('chatmoderator.emotes.filter.enabled', 'włączono filtr emotek.');
$.lang.register('chatmoderator.emotes.filter.disabled', 'wyłączono filtr emotek.');
$.lang.register('chatmoderator.colors.usage', 'jak używać: !moderation colors [on / off] (filtr kolorów jest teraz $1)');
$.lang.register('chatmoderator.colors.filter.enabled', 'włączono filtr kolorów.');
$.lang.register('chatmoderator.colors.filter.disabled', 'wyłączono filtr kolorów.');
$.lang.register('chatmoderator.regulars.usage', 'jak używać: !moderation regulars [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [true / false]');
$.lang.register('chatmoderator.subscribers.usage', 'jak używać: !moderation subscribers [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [true / false]');
$.lang.register('chatmoderator.subscribers.links.allowed', 'filtr linków został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.links.not.allowed', 'filtr linków został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.caps.allowed', 'filtr wielkich liter został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.caps.not.allowed', 'filtr wielkich liter został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.symbols.allowed', 'filtr symboli został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.symbols.not.allowed', 'filtr symboli został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.spam.allowed', 'filtr spamu został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.spam.not.allowed', 'filtr spamu został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.emotes.allowed', 'filtr emotek został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.emotes.not.allowed', 'filtr emotek został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.spamtracker.allowed', 'filtr śledzenia spamu został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.spamtracker.not.allowed', 'filtr śledzenia spamu został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.colors.allowed', 'filtr kolorów został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.colors.not.allowed', 'filtr kolorów został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.long.messages.allowed', 'filtr długich wiadomości został włączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.long.messages.not.allowed', 'filtr długich wiadomości został wyłączony dla subskrybentów.');
$.lang.register('chatmoderator.subscribers.toggle.link', 'wstawianie linków przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.caps', 'pisanie wielkimi literami przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.symbols', 'wstawianie symboli przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.spam', 'spamowanie przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.emotes', 'wstawianie dużej ilości emotek przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.colors', 'kolorowe pisanie przez subskrybentów jest $1.');
$.lang.register('chatmoderator.subscribers.toggle.long.msg', 'pisanie długich wiadomości przez subskrybentów jest $1.');
$.lang.register('chatmoderator.regulars.links.allowed', 'filtr linków został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.links.not.allowed', 'filtr linków został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.caps.allowed', 'filtr wielkich liter został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.caps.not.allowed', 'filtr wielkich liter został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.symbols.allowed', 'filtr symboli został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.symbols.not.allowed', 'filtr symboli został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.spam.allowed', 'filtr spamu został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.spam.not.allowed', 'filtr spamu został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.emotes.allowed', 'filtr emotek został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.emotes.not.allowed', 'filtr emotek został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.spamtracker.allowed', 'filtr śledzenia spamu został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.spamtracker.not.allowed', 'filtr śledzenia spamu został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.colors.allowed', 'filtr kolorowego pisania został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.colors.not.allowed', 'filtr kolorowego pisania został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.long.messages.allowed', 'filtr długich wiadomości został włączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.long.messages.not.allowed', 'filtr długich wiadomości został wyłączony dla stałych bywalców.');
$.lang.register('chatmoderator.regulars.toggle.link', 'wstawianie linków przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.caps', 'pisanie wielkimi literami przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.symbols', 'wstawianie symboli przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.spam', 'spamowanie przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.emotes', 'wstawianie dużej ilości emotek przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.colors', 'kolorowe pisanie przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.regulars.toggle.long.msg', 'pisanie długich wiadomości przez stałych bywalców jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.links', 'cichy timeout jest teraz $1.');
$.lang.register('chatmoderator.silenttimeout.usage.all', 'jak używać: !moderation silenttimeout all [true / false]');
$.lang.register('chatmoderator.silenttimeout.true', 'cichy timeout został włączony dla wszystkich filtrów.');
$.lang.register('chatmoderator.silenttimeout.false', 'cichy timeout został wyłączony dla wszystkich filtrów.');
$.lang.register('chatmoderator.silenttimeout.toggle.caps', 'cichy timeout dla wielkich liter jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.spamtracker', 'cichy timeout dla śledzenia spamu jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.symbols', 'cichy timeout dla symboli jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.spam', 'cichy timeout dla spamu jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.emotes', 'cichy timeout dla emotek jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.colors', 'cichy timeout dla pisania kolorem jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.long.message', 'cichy timeout dla pisania długich wiadomości jest $1.');
$.lang.register('chatmoderator.silenttimeout.toggle.blacklist', 'cichy timeout dla czarnej listy jest $1.');
$.lang.register('chatmoderator.silenttimeout.links.true', 'cichy timeout został włączony dla linków.');
$.lang.register('chatmoderator.silenttimeout.caps.true', 'cichy timeout został włączony dla wielkich liter.');
$.lang.register('chatmoderator.silenttimeout.symbols.true', 'cichy timeout został włączony dla symboli.');
$.lang.register('chatmoderator.silenttimeout.spam.true', 'cichy timeout został włączony dla spamu.');
$.lang.register('chatmoderator.silenttimeout.spamtracker.true', 'cichy timeout został włączony dla śledzenia spamu.');
$.lang.register('chatmoderator.silenttimeout.emotes.true', 'cichy timeout został włączony dla emotek.');
$.lang.register('chatmoderator.silenttimeout.colors.true', 'cichy timeout został włączony dla pisania kolorem.');
$.lang.register('chatmoderator.silenttimeout.long.msg.true', 'cichy timeout został włączony dla długich wiadomości.');
$.lang.register('chatmoderator.silenttimeout.links.false', 'cichy timeout został wyłączony dla linków.');
$.lang.register('chatmoderator.silenttimeout.caps.false', 'cichy timeout został wyłączony dla wielkich liter.');
$.lang.register('chatmoderator.silenttimeout.symbols.false', 'cichy timeout został wyłączony dla symboli.');
$.lang.register('chatmoderator.silenttimeout.spam.false', 'cichy timeout został wyłączony dla spamu.');
$.lang.register('chatmoderator.silenttimeout.spamtracker.false', 'cichy timeout został wyłączony dla śledzenia spamu.');
$.lang.register('chatmoderator.silenttimeout.emotes.false', 'cichy timeout został wyłączony dla emotek.');
$.lang.register('chatmoderator.silenttimeout.colors.false', 'cichy timeout został wyłączony dla pisania kolorem.');
$.lang.register('chatmoderator.silenttimeout.long.msg.false', 'cichy timeout został wyłączony dla długich wiadomości.');
$.lang.register('chatmoderator.silenttimeout.blacklist.messages.false', 'cichy timeout został wyłączony dla czarnej listy.');
$.lang.register('chatmoderator.silenttimeout.blacklist.messages.true', 'cichy timeout został włączony dla czarnej listy.');
$.lang.register('chatmoderator.silenttimeout.usage', 'jak używać: !moderation silenttimeout [links / caps / symbols / spam / emotes / colors / longmessages / blacklist / spamtracker / all] [true / false]');
$.lang.register('chatmoderator.link.message.usage', 'jak używać: !moderation linksmessage [message]');
$.lang.register('chatmoderator.link.message.set', 'ostrzeżenie o wstawianiu linków ustawiono na: $1');
$.lang.register('chatmoderator.caps.message.usage', 'jak używać: !moderation capsmessage [message]');
$.lang.register('chatmoderator.caps.message.set', 'ostrzeżenie o pisaniu wielkimi literami ustawiono na: $1');
$.lang.register('chatmoderator.symbols.message.usage', 'jak używać: !moderation symbolsmessage [message]');
$.lang.register('chatmoderator.symbols.message.set', 'ostrzeżenie o wstawianiu symboli ustawiono na: $1');
$.lang.register('chatmoderator.emotes.message.usage', 'jak używać: !moderation emotesmessage [message]');
$.lang.register('chatmoderator.emotes.message.set', 'ostrzeżenie o wstawianiu emotek ustawiono na: $1');
$.lang.register('chatmoderator.spam.message.usage', 'jak używać: !moderation spammessage [message]');
$.lang.register('chatmoderator.spam.message.set', 'ostrzeżenie o spamowaniu ustawiono na: $1');
$.lang.register('chatmoderator.spamtracker.message.usage', 'jak używać: !moderation spamtrackermessage [message]');
$.lang.register('chatmoderator.spamtracker.message.set', 'ostrzeżenie o włączeniu śledzenia spamu ustawiono na: $1');
$.lang.register('chatmoderator.colors.message.usage', 'jak używać: !moderation colorsmessage [message]');
$.lang.register('chatmoderator.colors.message.set', 'ostrzeżenie o pisaniu kolorem ustawiono na: $1');
$.lang.register('chatmoderator.blacklist.message.usage', 'jak używać: !moderation blacklistmessage [message]');
$.lang.register('chatmoderator.blacklist.message.set', 'ostrzeżenie o czarnej liście ustawiono na: $1');
$.lang.register('chatmoderator.permit.time.usage', 'jak używać: !moderation permittime [time]');
$.lang.register('chatmoderator.permit.time.set', 'pozwolenie na wstawianie linków ustawiono na: $1 sekund.');
$.lang.register('chatmoderator.caps.limit.usage', 'jak używać: !moderation capslimit [amount in percent]');
$.lang.register('chatmoderator.caps.limit.set', 'limit wielkich liter ustawiono na: $1% wielkich liter.');
$.lang.register('chatmoderator.caps.trigger.length.set', 'filtr wielkich liter aktywuje się po $1 wielkich literach.');
$.lang.register('chatmoderator.caps.trigger.length.usage', 'jak używać: !moderation capstriggerlength [amount]');
$.lang.register('chatmoderator.spam.limit.usage', 'jak używać: !moderation spamlimit [amount]');
$.lang.register('chatmoderator.spam.limit.set', 'limit spamu ustawiono na: $1');
$.lang.register('chatmoderator.spamtracker.limit.usage', 'jak używać: !moderation spamtrackerlimit [amount]');
$.lang.register('chatmoderator.spamtracker.limit.set', 'limit śledzenia spamu ustawiono na $1 wiadomości.');
$.lang.register('chatmoderator.spamtracker.time.usage', 'jak używać: !moderation spamtrackertime [amount in seconds]');
$.lang.register('chatmoderator.spamtracker.time.set', 'śledzenie spamu ustawiono na $1 sekund.');
$.lang.register('chatmoderator.symbols.limit.usage', 'jak używać: !moderation symbolslimit [amount]');
$.lang.register('chatmoderator.symbols.limit.set', 'limit symboli ustawiono na $1% symboli.');
$.lang.register('chatmoderator.symbols.group.limit.usage', 'jak używać: !moderation symbolsgrouplimit [amount]');
$.lang.register('chatmoderator.symbols.group.limit.set', 'grupowe wstawianie symboli ograniczono do $1 symboli.');
$.lang.register('chatmoderator.symbols.trigger.length.usage', 'jak używać: !moderation symbolsTriggerLength [amount]');
$.lang.register('chatmoderator.symbols.trigger.length.set', 'ograniczenie symboli uaktywni się po wstawieniu $1 symboli.');
$.lang.register('chatmoderator.emotes.limit.usage', 'jak używać: !moderation emoteslimit [amount]');
$.lang.register('chatmoderator.emotes.limit.set', 'limit emotek ustawiono na $1 emotek.');
$.lang.register('chatmoderator.permit.usage', 'jak używać: !permit [username]');
$.lang.register('chatmoderator.permited', ' może wstawiać linki przez kolejne $1 sekund.');
$.lang.register('chatmoderator.blacklist.usage', 'jak używać: !blackList [add / remove / show]');
$.lang.register('chatmoderator.blacklist.add.usage', 'jak używać: !blackList add (message)');
$.lang.register('chatmoderator.blacklist.added', 'Słowo zostało dodane do czarnej listy.');
$.lang.register('chatmoderator.blacklist.remove.usage', 'jak używać: !blackList remove (id)');
$.lang.register('chatmoderator.err', 'Nie ma takiego id.');
$.lang.register('chatmoderator.blacklist.removed', 'Słowo zostało usunięte z czarnej listy.');
$.lang.register('chatmoderator.blacklist.show.usage', 'jak używać: !blackList show (id)');
$.lang.register('chatmoderator.whitelist.usage', 'jak używać: !whiteList [add / remove / show]');
$.lang.register('chatmoderator.whitelist.add.usage', 'jak używać: !whiteList add (url)');
$.lang.register('chatmoderator.whitelist.link.added', 'Link został dodany do białej listy.');
$.lang.register('chatmoderator.whitelist.remove.usage', 'jak używać: !whiteList remove (id)');
$.lang.register('chatmoderator.whitelist.removed', 'Link został usunięty z białej listy.');
$.lang.register('chatmoderator.whitelist.show.usage', 'jak używać: !whiteList show (id)');
$.lang.register('chatmoderator.warning', '(ostrzeżenie)');
$.lang.register('chatmoderator.timeout', '(timeout)');
$.lang.register('chatmoderator.blacklisttimeouttime.set', 'timeout z czarnej listy ustawiono na $1 sekund.');
$.lang.register('chatmoderator.blacklisttimeouttime.usage', 'jak używać: !moderation blacklisttimeouttime [time in seconds] (blacklist timeout time is currently $1 seconds)');
$.lang.register('chatmoderator.warningtime.usage', 'jak używać: !moderation warningtime [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [time in seconds]');
$.lang.register('chatmoderator.warningtime.links.usage', 'jak używać: !moderation warning time links [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.links', 'długość czasu ostrzeżenia dla linków została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.caps.usage', 'jak używać: !moderation warning time caps [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.caps', 'długość czasu ostrzeżenia dla wielkich liter została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.symbols.usage', 'jak używać: !moderation warning time symbols [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.symbols', 'długość czasu ostrzeżenia dla symboli została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.spam.usage', 'jak używać: !moderation warning time spam [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.spam', 'długość czasu ostrzeżenia dla spamu została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.spamtracker.usage', 'jak używać: !moderation warning time spamtracker [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.spamtracker', 'długość czasu ostrzeżenia dla śledzenia spamu została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.colors.usage', 'jak używać: !moderation warning time colors [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.colors', 'długość czasu ostrzeżenia dla pisania kolorem została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.emotes.usage', 'jak używać: !moderation warning time emotes [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.emotes', 'długość czasu ostrzeżenia dla emotek została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.warningtime.longmsg.usage', 'jak używać: !moderation warning time longmessages [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.warningtime.longmsg', 'długość czasu ostrzeżenia dla długich wiadomości została ustawiona na $1 sekund.');
$.lang.register('chatmoderator.timeouttime.usage', 'jak używać: !moderation timeouttime [links / caps / symbols / spam / emotes / colors / longmessages / spamtracker] [time in seconds]');
$.lang.register('chatmoderator.timeouttime.links.usage', '!jak używać: moderation timeout time links [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.links', 'długość timeoutów dla linków została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.caps.usage', 'jak używać: !moderation timeout time caps [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.caps', 'długość timeoutów dla wielkich liter została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.symbols.usage', 'jak używać: !moderation timeout time symbols [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.symbols', 'długość timeoutów dla symboli została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.spam.usage', 'jak używać: !moderation timeout time spam [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.spam', 'długość timeoutów dla spamu została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.spamtracker.usage', 'jak używać: !moderation timeout time spamtracker [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.spamtracker', 'długość timeoutów dla śledzenia spamu została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.colors.usage', 'jak używać: !moderation timeout time colors [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.colors', 'długość timeoutów dla pisania kolorem została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.emotes.usage', 'jak używać: !moderation timeout time emotes [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.emotes', 'długość timeoutów dla emotek została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.longmsg.usage', 'jak używać: !moderation timeout time longmessages [time in seconds] (teraz ustawione na $1 sekund)');
$.lang.register('chatmoderator.timeouttime.longmsg', 'długość timeoutów dla długich wiadomości została ustawiona na $1.');
$.lang.register('chatmoderator.timeouttime.err', 'długość czasu timoutów dla śledzenia spamu nie może być mniejsza niż czas śledzenia spamu.');
$.lang.register('chatmoderator.warningtime.err', 'długość ostrzeżenia śledzenia spamu nie może być mniejsza niż czas śledzenia spamu.');
$.lang.register('cmd.404', 'komenda !$1 nie istnieje lub nie jest zarejestrowana.');
$.lang.register('cmd.adminonly', 'Tylko Administrator ma dostęp do tej komendy!');
$.lang.register('cmd.casteronly', 'Tylko Streamer ma dostęp do tej komendy!');
$.lang.register('cmd.modonly', 'Tylko Moderatorzy mają dostęp do tej komendy!');
$.lang.register('cmd.needpoints', 'Ta komenda kosztuje $1. Niestety nie masz tyle.');
$.lang.register('cmd.perm.404', 'tylko $1 ma dostęp do tej komendy.');
$.lang.register('commandlist.commands', 'Komendy (strona $1 z $2): $3');
$.lang.register('commandlist.more', ' >> Wpisz "!commands $1" aby wyświetlić więcej');
$.lang.register('commandlist.nocommands', 'Niesety nie ma komend dostępnych dla Ciebie.');
$.lang.register('commandlist.nopage', 'strona $1 nie istnieje.');
$.lang.register('commandlist.progress', 'Eksportuje komendy... $1%');
$.lang.register('commandpause.ended', 'Wszystkie komendy są teraz aktywne.');
$.lang.register('commandpause.initiated', 'Wszystkie komendy dla $1 są nieaktywne.');
$.lang.register('commandpause.isactive', 'Wszystkie komendy są teraz nieaktywne.');
$.lang.register('common.disabled', 'nieaktywne');
$.lang.register('common.enabled', 'aktywne');
$.lang.register('common.user-error', 'Musisz wyznaczyć cel tej komendy.');
$.lang.register('common.user.404', 'Użytkownik "$1" jeszcze nie odwiedził tego kanału.');
$.lang.register('console.channel.ishosting', '$1 aktualnie hostuje $2.');
$.lang.register('console.received.clearchat', 'Dostał powiadomienie o czyszczeniu czatu od jtv');
$.lang.register('console.received.host.end', 'Dostał powiadomienie o zakończeniu hostowania od jtv');
$.lang.register('console.received.host.start', 'Dostał powiadomienie o rozpoczęciu hostowania $1 od jtv');
$.lang.register('console.received.irsprivmsg', 'Dostał prywatną wiadomość od $1: $2');
$.lang.register('console.received.purgetimeoutban', 'Dostał powiadomienie o purge/timeout/ban użytkownika $1 od jtv');
$.lang.register('console.received.r9k.end', 'Dostał powiadomienie o zakończeniu trybu r9k od jtv');
$.lang.register('console.received.r9k.start', 'Dostał powiadomienie o rozpoczęciu trybu r9k od jtv');
$.lang.register('console.received.slowmode.end', 'Dostał powiadomienie o zakończeniu trybu wolnego od jtv');
$.lang.register('console.received.slowmode.start', 'Dostał powiadomienie o rozpoczęciu ($1) trybu wolnego od jtv');
$.lang.register('console.received.subscriberonly.end', 'Dostał powiadomienie o zakończeniu trybu tylko dla subskrybentów od jtv');
$.lang.register('console.received.subscriberonly.start', 'Dostał powiadomienie o rozpoczęciu trybu tylko dla subskrybentów od jtv');
$.lang.register('cooldown.set.togglemodcooldown', 'Opóźnienie używania komend przez moderatorów ustawiono na $1.');
$.lang.register('cooldown.set.usage', 'jak używać: !cooldown [command] [time in seconds]');
$.lang.register('cooldown.global.usage', 'jak używać: !globalcooldowntime [time in seconds]');
$.lang.register('cooldown.global.toggle', 'ogólne opóźnienie używania komend ustawiono na $1.');
$.lang.register('cooldown.per.user.toggle', 'opóźnienie dla użytkownika ustawiono na $1.');
$.lang.register('cooldown.global.set', 'ogólne opóźnienie używania komend ustawiono na $1 sekund.');
$.lang.register('cooldown.removed', 'opóźnienie używania komendy $1 zostało usunięte.');
$.lang.register('cooldown.set', 'opóźnienie używania komendy !$1 zostało ustawione na $2 sekund.');
$.lang.register('init.cmsgset', 'Wiadomość na połączenie ustawiona!');
$.lang.register('init.module.404', 'Ten moduł nie istnieje lub nie został załadowany!');
$.lang.register('init.module.check.disabled', 'Moduł $1 jest wyłączony!');
$.lang.register('init.module.check.enabled', 'Moduł $1 jest włączony!');
$.lang.register('init.module.auto-disabled', 'Moduły powiązane z pointSystem zostały wyłączone. Sprawdź logi.');
$.lang.register('init.module.disabled', 'Moduł "$1" wyłączony!');
$.lang.register('init.module.enabled', 'Moduł "$1" włączony!');
$.lang.register('init.module.error', 'Moduł "$1" włączony, ale się nie włączył! Sprawdź logi!');
$.lang.register('init.module.list', 'Moduły (* są wyłączone): $1');
$.lang.register('init.module.list.total', 'Wszystkich stron: $1');
$.lang.register('init.module.usage', 'jak używać: !module list, !module enable [module name], !module disable [module name], !module status [module name]');
$.lang.register('init.reconnect', 'Podłączam się ponownie do $1');
$.lang.register('init.rejoin', 'Podłączam ponownie do kanału.');
$.lang.register('init.disconnect', 'Odłączam się od $1');
$.lang.register('init.usage', '!$1 [reconnect / disconnect / connectmessage / removeconnectmessage / blacklist]');
$.lang.register('init.connected.msg', 'Wiadomość na połączeniu ustawiona na: $1');
$.lang.register('init.connected.msg.usage', '!$1 connectmessage [message]');
$.lang.register('init.connected.msg.removed', 'Wiadomość na połączeniu została wyłączona!');
$.lang.register('init.blacklist.usage', 'jak używać: !$1 blacklist [add / remove]');
$.lang.register('init.blacklist.add.usage', 'jak używać: !$1 blacklist add (username)');
$.lang.register('init.blacklist.added', '$1 dodano do czarnej listy!');
$.lang.register('init.blacklist.remove.usage', 'jak używać: !$1 blacklist remove (username)');
$.lang.register('init.blacklist.err', 'ten użytkownik nie jest na czarnej liście.');
$.lang.register('init.blacklist.removed', '$1 usunięto z czarnej listy.');
$.lang.register('init.mod.toggle.on.pay', 'moderatorzy+ będą od teraz płacić za komendy.');
$.lang.register('init.mod.toggle.off.pay', 'moderatorzy+ nie będą od teraz płacić za komendy.');
$.lang.register('init.mod.toggle.perm.msg.off', 'Wszystkie powiadomienia o ostrzeżeniach są włączone.');
$.lang.register('init.toggle.cooldown.msg.on', 'Powiadomienie o opóźnieniu zostało włączone.');
$.lang.register('init.toggle.cooldown.msg.off', 'Powiadomienie o opóźnieniu zostało wyłączone.');
$.lang.register('init.cooldown.msg', 'komenda !$1 jest wciąż opóźniona o $2 sekund.');
$.lang.register('lang.curlang', 'Język ustawiono na $1!');
$.lang.register('lang.lang.404', 'Plik językowy nie istnieje!');
$.lang.register('lang.lang.changed', 'Zmieniono język na $1!');
$.lang.register('lang.response.action.disabled', 'Czat będzie wyświetlany jako zwykły tekst. (bez /me)');
$.lang.register('lang.response.action.enabled', 'Czat będzie wyświetlany z przedrostkiem "/me".');
$.lang.register('lang.response.disabled', 'Odpowiedzi są teraz wyłączone. Aby je włączyć użyj komendy !mute');
$.lang.register('lang.response.enabled', 'Odpowiedzi są teraz włączone. Aby je wyłączyć użyj komendy !mute');
$.lang.register('logging.enabled.files', 'Zapisywanie czatu i plików zostało włączone.');
$.lang.register('logging.disabled.files', 'Zapisywanie czatu i plików zostało wyłączone.');
$.lang.register('logging.enabled.event', 'Zapisywanie wydarzeń zostało włączone.');
$.lang.register('logging.disabled.event', 'Zapisywanie wydarzeń zostało wyłączone.');
$.lang.register('logging.enabled.error', 'Zapisywanie błędów zostało włączone.');
$.lang.register('logging.disabled.error', 'Zapisywanie błędów zostało włączone.');
$.lang.register('logging.usage', 'jak używać: !log [files / errors / events]');
$.lang.register('logging.rotatedays.usage', 'jak używać: !log rotatedays [days]. 0 to keep all logs. Currently: $1');
$.lang.register('logging.rotatedays.success', 'Zapisane informacje będą zmieniać się po $1 dniach.');
$.lang.register('logging.rotatedays.success.off', 'Zapisane wiadomości nie będą się zmieniać.');
$.lang.register('permissions.current.listtoolong', 'Jest ponad $1 do zapisania na listę. Sugeruję sprawdzić listę widzów na Twitchu.');
$.lang.register('permissions.current.mods', 'Moderatorzy na kanale: $1');
$.lang.register('permissions.current.users', 'Widzowie na kanale: $1');
$.lang.register('permissions.group.self.current', 'W tej chwili posiadasz $1 uprawnień.');
$.lang.register('permissions.group.set.error.abovegroup', 'Musisz mieć wyższe uprawnienia niż osoba, której chcesz nadać uprawnienia.');
$.lang.register('permissions.group.set.error.samegroup', 'Nie możesz promować osoby do tego samego poziomu uprawnień jaki masz sam.');
$.lang.register('permissions.group.set.success', 'Uprawnienia dla $1 zmieniono na $2!');
$.lang.register('permissions.group.usage', 'jak używać: !permission, !permission [name] [permissionID]');
$.lang.register('permissions.grouppoints.usage', 'jak używać: !permissionpoints [group] [online|offline] [points]. points of -1 uses !setgain, !setofflinegain values.');
$.lang.register('permissions.grouppoints.showgroup', 'Uprawnienia $1 zyskują $2 $3 online oraz $4 $5 offline.');
$.lang.register('permissions.grouppoints.showgroup.online', '$1 zyskują $2 $3 online.');
$.lang.register('permissions.grouppoints.showgroup.offline', '$1 zyskują $2 $3 offline.');
$.lang.register('permissions.grouppoints.set.online', 'Ustaw uprawnienia $1 dostają $2 $3 online.');
$.lang.register('permissions.grouppoints.set.offline', 'Ustaw uprawnienia $1 dostają $2 $3 offline.');
$.lang.register('timesystem.uptime.offline', '$1 w tej chwili jest offline.');
$.lang.register('timesystem.uptime', '$1 jest live od $2!');
$.lang.register('timesystem.add.error.negative', 'Nie możesz użyć ujemnego czasu.');
$.lang.register('timesystem.add.success', 'Wysłał $1 dla $2. Nowe saldo to: $3.');
$.lang.register('timesystem.add.usage', 'jak używać: "!time give [name] [amount]"');
$.lang.register('timesystem.autolevel.disabled', 'Użytkownicy będący na czacie $2 godzin, nie będą promowani do $1.');
$.lang.register('timesystem.autolevel.enabled', 'Użytkownicy będący na czacie $2 godzin, będą promowani do $1.');
$.lang.register('timesystem.autolevel.promoted', '$1 dostał promocję do $2 będąc na czacie przez $3 godzin. Gratulacje!');
$.lang.register('timesystem.get.other', '$1 spędził $2 godzin na czacie.');
$.lang.register('timesystem.get.self', 'spędziłeś $2 godzin na czacie.');
$.lang.register('timesystem.modpermtoggle.success', 'Użytkownicy z grupy $1 lub wyższej, mogą teraz zarządzać komendami czasowymi.');
$.lang.register('timesystem.offlinetime.disabled', 'Czas offline nie będzie wliczany do czasu spędzonego na streamie.');
$.lang.register('timesystem.offlinetime.enabled', 'Czas offline będzie wliczany do czasu spędzonego na streamie.');
$.lang.register('timesystem.set.promotehours.error.negative', 'Nie możesz ustawić czasu w godzinach aby wypromować użytkonika $1 ujemnymi godzinami.');
$.lang.register('timesystem.set.promotehours.success', 'Wyznacz czas w godzinach aby wypromować użytkownika z $1 do $2.');
$.lang.register('timesystem.set.promotehours.usage', 'jak używać: "!time promotehours [amount]"');
$.lang.register('timesystem.set.timezone.invalid', '"$1" nie jest strefą czasową. Lista wszystkich stref czasowych jest dostępna pod adresem: "http://en.wikipedia.org/wiki/List_of_tz_database_time_zones".');
$.lang.register('timesystem.set.timezone.success', 'Strefa czasowa została ustawiona na: "$1". Automatycznie bierz pod uwagę czas letni/zimowy: $2');
$.lang.register('timesystem.set.timezone.usage', 'jak używać: !timezone [timezone name] (Current timezone is $1)');
$.lang.register('timesystem.settime.error.negative', 'Nie możesz ustawić ujemnego czasu.');
$.lang.register('timesystem.settime.success', 'Ustaw czas $1 na $2.');
$.lang.register('timesystem.settime.usage', 'jak używać: "!time set [name] [amount]"');
$.lang.register('timesystem.streamertime', 'U $2 jest teraz godzina $1.');
$.lang.register('timesystem.take.error.toomuch', 'Nie możesz wziąć wiecej niż $1 ma czasu.');
$.lang.register('timesystem.take.success', 'Wziął $1 od $2. Nowe saldo to: $3.');
$.lang.register('timesystem.take.usage', 'jak używać: "!time take [name] [amount]"');
$.lang.register('get.long.time.string.short', ' $1 dni, $2 godzin i $3 minut.');
$.lang.register('get.long.time.string.long', '$1 miesięcy, $2 godzin i $3 minut.');
$.lang.register('user.time.string.hours', ' $1 godzin i $2 minut');
$.lang.register('user.time.string.minutes', ' $1 minut');
$.lang.register('whisper.whispers.disabled', '[Tryb Szeptów] został wyłączony.');
$.lang.register('whisper.whispers.enabled', '[Tryb Szeptów] został włączony.');
$.lang.register('pausecommands.usage', 'jak używać: !pausecommands [seconds | clear]');
$.lang.register('common.hours', ' godzin, ');
$.lang.register('common.hours2', ' godzin, ');
$.lang.register('common.hours3', ' godzin');
$.lang.register('common.minutes', ' minut i ');
$.lang.register('common.minutes2', ' minut.');
$.lang.register('common.seconds', ' sekund');
$.lang.register('common.get.age.days', '$1 $2 jest na Twitchu od $3. (Dołączył $4 dni temu)');
$.lang.register('common.get.age', '$1 $2 jest na Twitchu od $3.');